image: gcc:latest

stages:
  - build
  - test

variables:
  CMAKE_BUILD_TYPE: "Release"

build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y cmake
    - mkdir -p build && cd build
    - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE
    - make -j2
  artifacts:
    paths:
      - build/App.exe
      - build/HashTest.exe
    expire_in: 1 week

test:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y cmake
    - cd build
    - ./HashTest.exe
  dependencies:
    - build